openapi: 3.0.0
info:
  version: 1.0.0
  title: REST API
  contact:
    name: Alexandr Saevich
    email: saleksandr19121998@gmail.com
    url: biba_i_bboba.com
servers:
  - url: 'https://aviasalo.com/v1.0'
    description: Live Server
tags:
  - name: Раздел
    description: |
      Описание раздела
      в несколько
      строк
security:
  - SecretApiKey: [] 
  - JWT: []
paths:
  /auth:
    $ref: './paths/auth.yaml'
  '/flight':
    $ref: './paths/flight.yaml'
  '/flight/{flightId}':
    $ref: './paths/flight@{flightId}.yaml'
  '/flights':
    $ref: './paths/flights.yaml'
  '/flight/{flightId}/tariffs':
    $ref: './paths/flight@{flightId}@tariffs.yaml'
  '/tariff':
    $ref: './paths/tariff.yaml'
  '/tariff/{tariffId}':
    $ref: './paths/tariff@{tariffId}.yaml'

